server:
  port: 10900

spring:
  datasource:
    # 新版驱动从com.mysql.jdbc.Driver变更为com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源需要添加时间标准和指定编码格式解决乱码 You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  profiles:
    active: dev

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

my:
  name: yanger
  girl:
    name: xiaohong
    age: 22

